name: dangple_mobile_tracker
description: "package to track user's location."
version: 1.0.0
homepage: https://github.com/dangple-kr
repository: https://github.com/dangple-kr/dangple-mobile-tracker

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  pedometer: ^4.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
